fieldLayouts:
  fb95ca4c-d4d2-497a-b711-07045e7d44e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27fe63a2-e7ed-40d5-aba7-4fe62283fb4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 09d594d1-9dad-4b34-95f0-16190f8f43a6 # identifier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45d002ee-73bb-4bf6-abcf-8ab8ba005b7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92eed38e-84b5-4eb5-ad88-7db8f09069e9 # Opening Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6367c0d1-1769-4fee-b7ab-7c1e428eca4b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 129fe766-beb4-4dc2-ac6b-020e0a1e82b6
        userCondition: null
handle: hours
hasTitleField: true
name: hours
section: b8823e8b-261b-4150-8e28-8ddb3bed4b69 # hours
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
